# .travis.yml

os: linux
dist: xenial
language: node_js
node_js:
  - 14

cache:
  directories:
    - node_modules

before_install:
  - npm install -g yarn

install:
  - yarn install

script:
  - yarn build

branches:
  only:
    - main

notifications:
  email: false
